FROM python:alpine

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TIMEZONE=Asia/Shanghai
ENV PYTHONUNBUFFERED=x

RUN set -eux \
  ; apk update && apk upgrade \
  ; rm -rf /var/cache/apk/* \
  ; apk add --no-cache tzdata \
  ; ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
  ; echo "$TIMEZONE" > /etc/timezone \
  ; pip3 --no-cache-dir install \
      pydantic \
      fastapi uvicorn httpx aiofile \
      PyParsing decorator more-itertools \
      typer structlog pyyaml cachetools chronyk \
      psycopg[binary]

WORKDIR /app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]


